# Generated by Django 4.0.2 on 2022-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('H', 'High'), ('M', 'Medium')], max_length=50),
        ),
    ]
